Add detect_arch() and replace_substring().

diff --git a/lib/shell b/lib/shell
--- a/lib/shell
+++ b/lib/shell
@@ -61,12 +61,36 @@ command_present() {
 ##
 detect_all() {
 	_e='0'
+	detect_arch || _e='1'
 	detect_distro || _e='1'
 	detect_init || _e='1'
 	detect_kernel || _e='1'
 	detect_release || _e='1'
 
 	return "$_e"
+}
+
+
+##
+# Detect architecture of running system.
+#
+# **Usage:** detect_arch
+#
+# **Returns:** true if detection succeeds
+#
+# **Exports:** H_ARCH
+#
+# .. code-block:: sh
+#
+#    detect_arch || die 'Architecture is not supported'
+##
+detect_arch() {
+	if command_present 'uname'; then
+		H_ARCH="$(uname -m)"; export H_ARCH
+		return 0
+	fi
+
+	return 1
 }
 
 
@@ -81,7 +105,7 @@ detect_all() {
 #
 # .. code-block:: sh
 #
-#    detect_distro || die 'Distro is not supported'
+#    detect_distro || die 'Distribution is not supported'
 ##
 detect_distro() {
 	if [ -n "$H_KERNEL" ]; then
@@ -108,28 +132,37 @@ detect_distro() {
 _distro_lsb() {
 	H_DISTRO="$(to_lower "$(lsb_release --short --id)")"
 	export H_DISTRO
+	return 0
 }
 
 # Detect release from /etc/*release* file
 _distro_release() {
 	if command_present 'awk'; then
 		H_DISTRO="$(to_lower "$(awk -F '=' '/^ID=/{print $2}' /etc/os-release)")"
+		if [ -n "$H_DISTRO" ]; then
+			export H_DISTRO
+			return 0
+		fi
+	fi;if command_present 'sed'; then
 		H_DISTRO="$(printf '%s' "$H_DISTRO" | sed 's/"//g')"
 		if [ -n "$H_DISTRO" ]; then
 			export H_DISTRO
 			return 0
 		fi
 	fi
+	return 1
 }
 
 # Detect release of Mac systems
 _distro_swvers() {
 	H_DISTRO='macosx'; export H_DISTRO
+	return 0
 }
 
 # Detect release of FreeBSD systems
 _distro_freebsd() {
 	H_DISTRO='freebsd'; export H_DISTRO
+	return 0
 }
 
 
@@ -210,16 +243,12 @@ _init_sbin() {
 ##
 detect_kernel() {
 	if command_present 'uname'; then
-		_kern_uname && return 0
+		H_KERNEL="$(to_lower "$(uname -s)")"
+		export H_KERNEL
+		return 0
 	fi
 
 	return 1
-}
-
-# Use uname output to detect kernel.
-_kern_uname() {
-	H_KERNEL="$(to_lower "$(uname -s)")"
-	export H_KERNEL
 }
 
 
@@ -397,7 +426,7 @@ in_string() {
 #    internet_accessible || die 'Cannot reach the internet'
 ##
 internet_reachable() {
-	PING_HOST="${PING_HOST:-google.com/}"
+	PING_HOST="${PING_HOST:-google.com}"
 	PING_ADDR="${PING_ADDR:-8.8.8.8}"
 	if command_present 'wget'; then
 		wget -q --spider "http://$PING_HOST/" && return 0
@@ -658,6 +687,30 @@ log() {
 
                 printf '*** %s: %s ***\n' "$_lvl" "$2"
         fi
+}
+
+
+##
+# Find/replace substrings in a string.
+#
+# **Usage:** replace_substring input find repl
+#
+# - input: full string to be manipulated
+# - find: key to search for
+# - repl: what to replace "key" with
+#
+# **Prints:** modified string
+#
+# .. code-block:: sh
+#
+#    log "$E" "$(replace_substring "$err" "$secret" '****')"
+##
+replace_substring() {
+	if command_present 'awk'; then
+		printf '%s' "$1" | awk -v f="$2" -v r="$3" 'gsub(f, r)'
+	else
+		die '7' 'Unable to replace_substring().'
+	fi
 }
 
 
diff --git a/tests/test_shell b/tests/test_shell
--- a/tests/test_shell
+++ b/tests/test_shell
@@ -8,21 +8,26 @@ TEST_DIR="$(dirname "$0")"; export TEST_DIR
 
 # Test shell
 TEST_SHELL="${TEST_SHELL:-sh}"
-printf 'Using shell: %s\n' "$TEST_SHELL"
 
 
 main() {
-	TESTS_FAILED='false'
+	C_FAILED=0
+	C_PASSED=0
+	# shellcheck disable=SC2126 #[grep -c doesn't work well here]
+	C_UNITS="$(grep 'exit 1' "$TEST_DIR/shell_units/"*/* | wc -l)"
+
+	# Header
+	printf '####\n# Running Tests\n#\tshell: %s\n####\n' \
+		"$TEST_SHELL"
 
 	# Run tests
 	run_tests 'Constant'
 	run_tests 'Function'
 
-	# Print summary
-	if [ "$TESTS_FAILED" = 'true' ]; then
-		printf '!!! One or more tests failed. !!!\n'
-		return 1
-	fi
+	# Summary
+	printf -- '####\n# TEST RESULTS: [ Failed: %s Passed: %s Tests: %s ]\n####\n' \
+		"$C_FAILED" "$C_PASSED" "$C_UNITS"
+	[ "$TESTS_FAILED" = 'true' ] && return 1
 	return 0
 }
 
@@ -39,9 +44,11 @@ run_tests() {
 		printf '%24s:\t' "$file"
 		if ! ("$TEST_SHELL" "$path"); then
 			printf 'FAILED\n'
+			C_FAILED="$((C_FAILED + 1))"
 			TESTS_FAILED='true'
 		else
 			printf 'Passed\n'
+			C_PASSED="$((C_PASSED + 1))"
 		fi
 	done
 }
